slam_toolbox:
  ros__parameters:
    # Frame configuration
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    
    # Topic configuration
    scan_topic: /scan
    
    # Mode configuration
    mode: localization  # 'localization' for racing with existing map
    
    # Queue and timing configuration to prevent message dropping
    scan_queue_size: 10
    transform_timeout: 0.2
    update_rate: 10.0
    tf_buffer_duration: 10.0
    
    # SLAM parameters
    resolution: 0.05
    min_laser_range: 0.10
    max_laser_range: 20.0
    minimum_time_interval: 0.1
    transform_publish_period: 0.02
    
    # Memory management
    max_queue_size: 10
    use_tree: true
    use_scan_matching: true
    use_scan_barycenter: true
    
    # Optimization parameters for localization
    linear_update: 0.1
    angular_update: 0.1
    linear_scan_update: 0.1
    angular_scan_update: 0.1
    
    # Localization specific parameters
    use_localization_smoothing: true
    localization_ang_range: 0.5
    localization_lin_range: 0.5
